### ISSUE TITLE
Agenda of the 2nd ModelWriter International Workshop in Brussels.

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/WP5#86]
- [x] Introduction:
 - [x] Invited Talk: Bernard Fontaine (Former ModelWriter Project Leader)
 - [x] The new partners: 
      - [x] Sogeti and their Industrial Use Cases (Philippe Bureille)
      - [x] Havelsan and their Industrial Use Case (Dr. Eray Tüzün)
      - [x] KU Leuven (Prof. Sien Moens and Prof. Monique Snoeck)
 - [x] The potential Belgian partners: 
      - [x] University of Antwerp and Verhaert (Prof. Hans Vangheluwe)
- [x] A meeting session for reviewing the requirements
 - [x] User Requirements
    - view on [Waffle](https://waffle.io/modelwriter/requirements?label=User%20Requirements%20Document%20(URD))
    - view on [GitHub](https://github.com/ModelWriter/Requirements/labels/User%20Requirements%20Document%20%28URD%29)
 - [ ] Software requirements
    - view on [Waffle](https://waffle.io/modelwriter/requirements?label=Software%20Requirements%20Document%20(SRD))
    - view on [GitHub](https://github.com/ModelWriter/Requirements/labels/Software%20Requirements%20Document%20%28SRD%29)
 - [x] Prioritizing the requirements	
- [x] Discussing the agenda deliverables:
 - [ ] [M8] D1.5.1 Minutes of the User Requirements Review meeting (ModelWriter/Project-Management#12)
 - [ ] [M8] D1.5.2 User Requirements Document (URD) (ModelWriter/Project-Management#11)
 - [ ] [M9] D1.6.1 Minutes of the Software Requirements Review meeting (ModelWriter/Project-Management#14)
 - [ ] [M9] D1.6.2 Software Requirements Document (ModelWriter/Project-Management#13)
 - [ ] [M9] D4.1.1 Knowledge Base Design document (ModelWriter/Project-Management#57)
 - [ ] [M9] D4.2.1 Interface Control Document (ICD) (ModelWriter/Project-Management#58)
 - [ ] [M8] D5.2.1 Project Progress Report (first half year) (ModelWriter/Project-Management#126)
 - [ ] [M9] D7.4.1 ModelWriter-ITEA website (ModelWriter/Project-Management#116)
 - [ ] [M8] D7.2.1-1 Exploitation and Marketing Plan (ModelWriter/Project-Management#110)
 - [ ] [M8] D2.3.1 Overview and comparison of existing generators (ModelWriter/Project-Management#21)
 - [ ] [M8] D3.1.1 Review of model-to-model transformation approaches and technologies (ModelWriter/Project-Management#33)
 - [ ] [M8] D3.2.1 M2M Transformation Framework architectural design document (ModelWriter/Project-Management#34)

View deliverables by milestones:
- [M8] (https://github.com/ModelWriter/Project-Management/milestones/M8)
- [M9] (https://github.com/ModelWriter/Project-Management/milestones/M9)

/cc @ModelWriter/consortium
